{% set name = "diffoscope" %}
{% set version = "99" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d204ac51cc8ae59de755e1be0f7600e52b59badc32969942af4684c3f6f3f03

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - diffoscope = diffoscope.main:main

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - python-libarchive-c
    - python-magic

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - diffoscope
  commands:
    - diffoscope --help
    - diffoscope --list-tools
    - diffoscope --version
    - |-
      pytest ./tests -k "\
        not assert_non_existing \
        and not berkeley_db \
        and not test_icc \
        and not test_item1_elf \
      "

about:
  home: https://diffoscope.org
  license: GPL-3.0
  summary: in-depth comparison of files, archives, and directories
  license_family: GPL
  license_file: COPYING
  dev_url: https://anonscm.debian.org/cgit/reproducible/diffoscope.git
  description: >
    diffoscope will try to get to the bottom of what makes files or
    directories different. It will recursively unpack archives of many kinds
    and transform various binary formats into more human readable form to
    compare them. It can compare two tarballs, ISO images, or PDF just as
    easily.

extra:
  recipe-maintainers:
    - bollwyvl
