travis:
  secure:
    BINSTAR_TOKEN: QiOU+ENnd9Uw5hEEYeg2jhh8it8G56cdeSo1IIDzEXny35/foV3F/UT21tI4Zs3YrItTnGYot+hi4I3hw9/NgpekP3QCIE+CKIL6fE99wBp4qBLsC3yRiM3/rq2hP4VvFZrjD5q3fYVNk8nfX2jvyB86TwFJ+b8Hdtc+xDiba4LsLGTmZ5FtMXHtX+eboUlQH5XnHEr0V0nAywikJmG2Ti4vR6HhuF5yF0HU4dx4PDe8SELOCE2zWn4M4YuFU4MMScN5c1K1Mnh23IMJZ7cZvgitZBCcJ35PqtFUN516XHHnnpJa6tDl2FD1sN2vsKiI/kMhT5Lq0Vfr1aJe6koz9TR0ZP6WJDJ6TLWW1wvicvSV1MDHS/WeWJDQdFtY1IlgfEPXN1wD/tXlhXPWCfbwDUla5jRDL6C+BEfG+f3YjK3joXow287yWVntedn8psUEs3uV4FEh+UbjleLvq9hE9P69HhqkcfudAiijCY9QcE5AkDXqE911CjLlCgLtwWWyFBupmAaikWXcFm8ITRQnuO/AgkVYHCcdS9mbxBHurQeXe1kDH9hWykOD4VLEYannPCqyLTWBRZsIz86PiyGOBVDGqUWJU3PZoPWukEBPmuDAKK0/UdqfBatZaj7ds389W5uYJ+hym879tupc2uvV00XQtd/O7GSXudQsS5fEYyk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
